#!/usr/bin/env bash
set -Eeuo pipefail

# iwlwifi-stability-fix.sh
# - Reinstall/upgrade linux-firmware (Intel Wi-Fi firmware)
# - Apply iwlmvm/iwlwifi power-save mitigation
# - Reload modules when possible
# - Produce before/after checks and a log

#######################################
# Config (flags)
#######################################
APPLY_FWUPD_UPDATES=0        # set to 1 with --apply-fwupd
DISABLE_BT_COEX=0            # set to 1 with --disable-bt-coex (optional)
DISABLE_40MHZ_24GHZ=0        # set to 1 with --disable-40mhz-24ghz (optional)

for arg in "$@"; do
  case "$arg" in
  --apply-fwupd) APPLY_FWUPD_UPDATES=1 ;;
  --disable-bt-coex) DISABLE_BT_COEX=1 ;;
  --disable-40mhz-24ghz) DISABLE_40MHZ_24GHZ=1 ;;
  -h|--help)
    cat <<'EOF'
Usage: sudo bash iwlwifi-stability-fix.sh [options]

Options:
  --apply-fwupd             Attempt to apply firmware updates via fwupdmgr (may require reboot)
  --disable-bt-coex         Set iwlwifi bt_coex_active=0 (may affect BT/Wi-Fi interference behavior)
  --disable-40mhz-24ghz     Set cfg80211 cfg80211_disable_40mhz_24ghz=Y (may improve 2.4GHz stability)
EOF
    exit 0
    ;;
  esac
done

#######################################
# Logging & helpers
#######################################
TS="$(date +%F_%H%M%S)"
LOGFILE="/var/log/iwlwifi-fix-${TS}.log"
exec > >(tee -a "$LOGFILE") 2>&1

err() { echo "[ERROR] $*" >&2; }
info() { echo "[INFO]  $*"; }
warn() { echo "[WARN]  $*"; }

trap 'err "Failed at line $LINENO: $BASH_COMMAND (exit $?)"; err "See log: $LOGFILE"' ERR

have_cmd() { command -v "$1" >/dev/null 2>&1; }

need_root() {
  if [[ "${EUID:-$(id -u)}" -ne 0 ]]; then
    err "Must be run as root (use sudo)."
    exit 1
  fi
}

apt_install() {
  local pkgs=("$@")
  export DEBIAN_FRONTEND=noninteractive
  if ! have_cmd apt-get; then
    err "apt-get not found (this script assumes Pop!/Ubuntu/Debian-family)."
    exit 1
  fi
  info "Installing prerequisites: ${pkgs[*]}"
  apt-get update -y || warn "apt-get update failed (network issue?). Continuing with local changes."
  apt-get install -y "${pkgs[@]}" || warn "apt-get install had issues. Continuing where possible."
}

kernel_log_since() {
  local since="$1"
  if have_cmd journalctl; then
    journalctl -k --since "$since" --no-pager || true
  else
    # fallback
    dmesg -T || true
  fi
}

#######################################
# Pre-run checks
#######################################
need_root

START_WALLCLOCK="$(date --iso-8601=seconds)"
info "Log file: $LOGFILE"
info "Start time: $START_WALLCLOCK"

apt_install pciutils iw rfkill network-manager linux-firmware fwupd

info "System:"
uname -a || true
cat /etc/os-release || true

info "Detecting Wi-Fi hardware/driver..."
lspci -nnk | grep -A3 -Ei 'Network controller|Wireless|Wi-Fi' || warn "No obvious Wi-Fi controller found in lspci output."

info "Current iwlwifi-related kernel messages (last 200 lines):"
(dmesg -T | tail -n 200 | grep -Ei 'iwlwifi|iwlmvm' || true)

info "NetworkManager state:"
(systemctl is-active NetworkManager && nmcli general status) || true

info "rfkill state:"
rfkill list || true

#######################################
# Apply fixes
#######################################
info "Reinstalling/refreshing linux-firmware (Intel Wi-Fi firmware package)..."
apt-get install -y --reinstall linux-firmware || warn "linux-firmware reinstall failed (network?)."

CONF="/etc/modprobe.d/99-iwlwifi-stability.conf"
BACKUP="${CONF}.bak.${TS}"

if [[ -f "$CONF" ]]; then
  info "Backing up existing $CONF to $BACKUP"
  cp -a "$CONF" "$BACKUP"
fi

info "Writing module options to $CONF"
{
  echo "# Generated by iwlwifi-stability-fix.sh on $TS"
  echo "# Workaround: disable Wi-Fi PCIe power-save transitions (recommended in Linux Wireless docs)."
  echo "options iwlmvm power_scheme=1"
  echo "# Extra: also disable iwlwifi power save (can improve stability at the cost of battery)."
  echo "options iwlwifi power_save=0"
  if [[ "$DISABLE_BT_COEX" -eq 1 ]]; then
    echo "# Optional: disable Bluetooth coexistence"
    echo "options iwlwifi bt_coex_active=0"
  fi
  if [[ "$DISABLE_40MHZ_24GHZ" -eq 1 ]]; then
    echo "# Optional: reduce 2.4GHz channel width instability"
    echo "options cfg80211 cfg80211_disable_40mhz_24ghz=Y"
  fi
} > "$CONF"

# Update initramfs if available (helps ensure options are honored early, if needed)
if have_cmd update-initramfs; then
  info "Updating initramfs..."
  update-initramfs -u || warn "update-initramfs failed."
fi

#######################################
# Reload driver (best effort)
#######################################
NEED_REBOOT=0

info "Attempting to reload iwlwifi/iwlmvm modules (best effort)..."
if have_cmd nmcli; then
  nmcli radio wifi off || true
  nmcli networking off || true
fi

systemctl stop NetworkManager || true
sleep 2

if lsmod | grep -q '^iwlmvm'; then
  modprobe -r iwlmvm || { warn "Could not unload iwlmvm (in use)."; NEED_REBOOT=1; }
fi
if lsmod | grep -q '^iwlwifi'; then
  modprobe -r iwlwifi || { warn "Could not unload iwlwifi (in use)."; NEED_REBOOT=1; }
fi

modprobe iwlwifi || { warn "Could not load iwlwifi."; NEED_REBOOT=1; }

systemctl start NetworkManager || true
sleep 3

if have_cmd nmcli; then
  nmcli networking on || true
  nmcli radio wifi on || true
fi

#######################################
# Firmware (fwupd) check
#######################################
info "Checking firmware updates (fwupd)..."
fwupdmgr refresh -y || warn "fwupdmgr refresh failed."
fwupdmgr get-updates || true

if [[ "$APPLY_FWUPD_UPDATES" -eq 1 ]]; then
  info "Attempting to apply firmware updates (fwupdmgr update)..."
  fwupdmgr update -y || warn "fwupdmgr update failed or requires interaction."
  NEED_REBOOT=1
else
  info "Not applying firmware updates automatically. Re-run with --apply-fwupd to attempt it."
fi

#######################################
# Post-run checks
#######################################
info "Post-run: verify module parameters (if modules loaded)..."
if [[ -r /sys/module/iwlmvm/parameters/power_scheme ]]; then
  info "iwlmvm power_scheme=$(cat /sys/module/iwlmvm/parameters/power_scheme)"
else
  warn "iwlmvm power_scheme parameter not readable (module may not be loaded)."
fi
if [[ -r /sys/module/iwlwifi/parameters/power_save ]]; then
  info "iwlwifi power_save=$(cat /sys/module/iwlwifi/parameters/power_save)"
fi

info "Post-run: Network status:"
nmcli device status || true

info "Post-run: Wi-Fi scan (may take a few seconds):"
timeout 20 nmcli dev wifi list || warn "Wi-Fi scan failed/timed out."

info "Post-run: recent iwlwifi kernel messages since start:"
kernel_log_since "$START_WALLCLOCK" | grep -Ei 'iwlwifi|iwlmvm|Microcode SW error|ADVANCED_SYSASSERT|SW reset|LMAC_FATAL' || true

# Basic connectivity check if we're connected
if have_cmd nmcli && nmcli -t -f DEVICE,STATE dev | grep -q ':connected'; then
  info "Post-run: ping test (1.1.1.1)"
  ping -c 3 -W 2 1.1.1.1 || warn "Ping failed (could be network/router/DNS)."
else
  warn "No connected interface detected; skipping ping test."
fi

if [[ "$NEED_REBOOT" -eq 1 ]]; then
  warn "One or more steps indicate a reboot is likely required to fully apply changes."
fi

info "Done. Review the log: $LOGFILE"
